# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
version: 2
before:
  hooks:
    - go mod tidy
builds:
  - id: linux-amd64
    env:
      - CGO_ENABLED=1
    main: ./cmd/fleeting-plugin-vcd/main.go
    goos:
      - linux
    goarch:
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - ids:
      - linux-amd64
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: ["binary"]
    # wrap_in_directory: true

checksum:
  name_template: "checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
